# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23dbfa7166e1aa32688f0ce2a2708cdbb10b6481e1205cbf98ee6953d8c128838d8fd1318533829f803d73e59379597d943789f7f229142e7860aea0c5192352
  secret_devise: 5bfde90079fe98480db6f77b522f2fb4b01fa03c271debcd21c2446dde02b97710a3585773641bff97025eeddd568c8f5eb13719b4891970b5a86b7f70c2b584
  google_oauth_id: <%= ENV["GOOGLE_OAUTH_ID"] %>
  google_oauth_secret: <%= ENV["GOOGLE_OAUTH_SECRET"] %>
  github_id: <%= ENV["GITHUB_ID"] %>
  github_secret: <%= ENV["GITHUB_SECRET"] %>
  mandrill_email: <%= ENV["MANDRILL_EMAIL"] %>
  mandrill_password: <%= ENV["MANDRILL_PASSWORD"] %>

test:
  secret_key_base: 96e1df5381e8cfa7513eae9c849b341717c672b5bba623189a82fc8b523eaafc21eb53422252ef6da7efa736dbd7190262af79da8b356c285a4dfbca0f54c804
  google_oauth_id: <%= ENV["GOOGLE_OAUTH_ID"] %>
  google_oauth_secret: <%= ENV["GOOGLE_OAUTH_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_oauth_id: <%= ENV["GOOGLE_OAUTH_ID"] %>
  google_oauth_secret: <%= ENV["GOOGLE_OAUTH_SECRET"] %>
  secret_devise: <%= ENV["SECRET_DEVISE"] %>
  github_id: <%= ENV["GITHUB_ID"] %>
  github_secret: <%= ENV["GITHUB_SECRET"] %>
  mandrill_email: <%= ENV["MANDRILL_EMAIL"] %>
  mandrill_password: <%= ENV["MANDRILL_PASSWORD"] %>
